-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 13:23:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `rolId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`rolId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `passsword` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `app` VARCHAR(45) NULL,
  `apm` VARCHAR(45) NULL,
  `dateInsert` DATE NULL,
  `rolId` INT NULL,
  INDEX `rolId_idx` (`rolId` ASC),
  PRIMARY KEY (`userId`),
  INDEX `username` (`username` ASC),
  CONSTRAINT `rolId`
    FOREIGN KEY (`rolId`)
    REFERENCES `mydb`.`roles` (`rolId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `productoId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `ean` VARCHAR(45) NULL,
  `codigoAlt` VARCHAR(45) NULL,
  `dateInsert` DATE NULL,
  `userInsert` INT NULL,
  PRIMARY KEY (`productoId`),
  INDEX `idIndex` (`userInsert` ASC),
  INDEX `nombreIndex` (`nombre` ASC),
  INDEX `eanIndex` (`ean` ASC),
  CONSTRAINT `userInsert`
    FOREIGN KEY (`userInsert`)
    REFERENCES `mydb`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoMovimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoMovimiento` (
  `tipoId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `dateInsert` DATE NULL,
  `userInsert` INT NULL,
  PRIMARY KEY (`tipoId`),
  INDEX `userInsert_idx` (`userInsert` ASC),
  CONSTRAINT `userInsert`
    FOREIGN KEY (`userInsert`)
    REFERENCES `mydb`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimientos` (
  `movimientoId` INT NOT NULL AUTO_INCREMENT,
  `productoId` INT NULL,
  `tipoMovimiento` INT NULL,
  `cantidad` INT NULL,
  `dateInsert` DATE NULL,
  `userInsert` INT NULL,
  PRIMARY KEY (`movimientoId`),
  INDEX `productoId_idx` (`productoId` ASC),
  INDEX `userInsert_idx` (`userInsert` ASC),
  INDEX `tipoMovimiento_idx` (`tipoMovimiento` ASC),
  CONSTRAINT `productoId`
    FOREIGN KEY (`productoId`)
    REFERENCES `mydb`.`productos` (`productoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userInsert`
    FOREIGN KEY (`userInsert`)
    REFERENCES `mydb`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoMovimiento`
    FOREIGN KEY (`tipoMovimiento`)
    REFERENCES `mydb`.`tipoMovimiento` (`tipoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_log` (
  `logId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NULL,
  `proceso` VARCHAR(45) NULL,
  `detalle` VARCHAR(45) NULL,
  `dateInsert` DATE NULL,
  PRIMARY KEY (`logId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reportes` (
  `reporteId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `dataProductos` BLOB NULL,
  `dateInsert` INT NULL,
  `dateUser` DATE NULL,
  PRIMARY KEY (`reporteId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`procesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`procesos` (
  `procesoId` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NULL,
  PRIMARY KEY (`procesoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_procesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles_procesos` (
  `roles_rolId` INT NOT NULL,
  `procesos_procesoId` INT NOT NULL,
  PRIMARY KEY (`roles_rolId`, `procesos_procesoId`),
  INDEX `fk_roles_has_procesos_procesos1_idx` (`procesos_procesoId` ASC),
  INDEX `fk_roles_has_procesos_roles1_idx` (`roles_rolId` ASC),
  CONSTRAINT `fk_roles_has_procesos_roles1`
    FOREIGN KEY (`roles_rolId`)
    REFERENCES `mydb`.`roles` (`rolId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_procesos_procesos1`
    FOREIGN KEY (`procesos_procesoId`)
    REFERENCES `mydb`.`procesos` (`procesoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
